//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.28 at 01:01:15 AM NOVT 
//


package com.vladimirkhil.ygpackage3_0;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.vladimirkhil.ygpackage3_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.vladimirkhil.ygpackage3_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Pack }
     * 
     */
    public Pack createPackage() {
        return new Pack();
    }

    /**
     * Create an instance of {@link Pack.Rounds }
     * 
     */
    public Pack.Rounds createPackageRounds() {
        return new Pack.Rounds();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round }
     * 
     */
    public Pack.Rounds.Round createPackageRoundsRound() {
        return new Pack.Rounds.Round();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes }
     * 
     */
    public Pack.Rounds.Round.Themes createPackageRoundsRoundThemes() {
        return new Pack.Rounds.Round.Themes();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme createPackageRoundsRoundThemesTheme() {
        return new Pack.Rounds.Round.Themes.Theme();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions createPackageRoundsRoundThemesThemeQuestions() {
        return new Pack.Rounds.Round.Themes.Theme.Questions();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions.Question }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions.Question createPackageRoundsRoundThemesThemeQuestionsQuestion() {
        return new Pack.Rounds.Round.Themes.Theme.Questions.Question();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions.Question.Scenario }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions.Question.Scenario createPackageRoundsRoundThemesThemeQuestionsQuestionScenario() {
        return new Pack.Rounds.Round.Themes.Theme.Questions.Question.Scenario();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions.Question.Type }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions.Question.Type createPackageRoundsRoundThemesThemeQuestionsQuestionType() {
        return new Pack.Rounds.Round.Themes.Theme.Questions.Question.Type();
    }

    /**
     * Create an instance of {@link InfoType }
     * 
     */
    public InfoType createInfoType() {
        return new InfoType();
    }

    /**
     * Create an instance of {@link Pack.Tags }
     * 
     */
    public Pack.Tags createPackageTags() {
        return new Pack.Tags();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions.Question.Right }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions.Question.Right createPackageRoundsRoundThemesThemeQuestionsQuestionRight() {
        return new Pack.Rounds.Round.Themes.Theme.Questions.Question.Right();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions.Question.Wrong }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions.Question.Wrong createPackageRoundsRoundThemesThemeQuestionsQuestionWrong() {
        return new Pack.Rounds.Round.Themes.Theme.Questions.Question.Wrong();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions.Question.Scenario.Atom }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions.Question.Scenario.Atom createPackageRoundsRoundThemesThemeQuestionsQuestionScenarioAtom() {
        return new Pack.Rounds.Round.Themes.Theme.Questions.Question.Scenario.Atom();
    }

    /**
     * Create an instance of {@link Pack.Rounds.Round.Themes.Theme.Questions.Question.Type.Param }
     * 
     */
    public Pack.Rounds.Round.Themes.Theme.Questions.Question.Type.Param createPackageRoundsRoundThemesThemeQuestionsQuestionTypeParam() {
        return new Pack.Rounds.Round.Themes.Theme.Questions.Question.Type.Param();
    }

    /**
     * Create an instance of {@link InfoType.Authors }
     * 
     */
    public InfoType.Authors createInfoTypeAuthors() {
        return new InfoType.Authors();
    }

    /**
     * Create an instance of {@link InfoType.Sources }
     * 
     */
    public InfoType.Sources createInfoTypeSources() {
        return new InfoType.Sources();
    }

}
