//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.28 at 01:01:15 AM NOVT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://vladimirkhil.com/ygpackage3.0.xsd", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vladimirkhil.ygpackage3_0;
